name: backend CI

on:
  pull_request:
    paths:
      - "backend/**"

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Commentout 'cv2.imwrite'
        run: sed -i -e '/cv2.imwrite/s/^/# /g' ./backend/controller/*.py

      - name: Run flake8
        uses: julianwachholz/flake8-action@v1.1.0
        with:
          checkName: "Python Lint"
          path: backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y upgrade
          apt-get install -y cmake
          apt-get install -y libgl1-mesa-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test
        run: python -m unittest discover tests/
        working-directory: ./backend

      - name: Set COMMIT_MESSAGE
        run: echo ::set-env name=COMMIT_MESSAGE::$(echo "${{ github.event.head_commit.message }}" | tr '\n' ' ')
      - name: Slack Notification on SUCCESS
        if: success()
        uses: tokorom/action-slack-incoming-webhook@master
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: Successfully automated deployment.
          attachments: |
            [
              {
                "color": "good",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "fields": [
                  {
                    "title": "Commit Message",
                    "value": "${{ env.COMMIT_MESSAGE }}"
                  }
                ]
              }
            ]
